# Configuração do servidor
server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 3000

#consiguração do spring cloud config
spring:
  spring:
    profiles:
      active: native
  #Dentro da conf do Spring Cloud fica a configuração do banco de dados
  data:
    mongodb:
      uri: mongodb://admin:superSecreta@localhost:27017/?authMechanism=SCRAM-SHA-256
      database: ProdutoDB
      auto-index-creation: true

Application-version: 0.1